#!/bin/bash
for file in *.html; do
    if [ ! -e "../$file" ] || [ "$file" -nt "../$file" ]; then
        cp "$file" "../$file"
    fi
done#!/bin/bash
for file in [A-Z]*; do
    mv "$file" /tmp/u/
done
